import type {
  AttendanceSession,
  BiometricRequest,
  CameraFeed,
  LecturerClass,
  LecturerKpi,
  LecturerStudent,
  ViolationAlert,
} from '../../types/lecturer';

/** Dữ liệu giả — lớp học của giảng viên */
export const MOCK_LECTURER_CLASSES: LecturerClass[] = [
  {
    id: 'cls-001',
    code: 'CS101',
    name: 'Introduction to Programming',
    facultyId: 'it',
    semester: 'HK1 2025-2026',
    schedule: 'Mon, Wed 08:00–10:00',
    room: 'B2-301',
    studentCount: 45,
    status: 'active',
    attendanceRate: 88.5,
  },
  {
    id: 'cls-002',
    code: 'CS201',
    name: 'Data Structures & Algorithms',
    facultyId: 'it',
    semester: 'HK1 2025-2026',
    schedule: 'Tue, Thu 13:30–15:30',
    room: 'A1-205',
    studentCount: 38,
    status: 'active',
    attendanceRate: 91.2,
  },
  {
    id: 'cls-003',
    code: 'CS301',
    name: 'Software Engineering',
    facultyId: 'it',
    semester: 'HK1 2025-2026',
    schedule: 'Fri 08:00–11:00',
    room: 'C3-102',
    studentCount: 32,
    status: 'active',
    attendanceRate: 85.7,
  },
  {
    id: 'cls-004',
    code: 'CS401',
    name: 'Capstone Project',
    facultyId: 'it',
    semester: 'HK1 2025-2026',
    schedule: 'Wed 14:00–17:00',
    room: 'Lab-4',
    studentCount: 28,
    status: 'upcoming',
    attendanceRate: 0,
  },
  {
    id: 'cls-005',
    code: 'ECO101',
    name: 'Microeconomics',
    facultyId: 'economics',
    semester: 'HK1 2025-2026',
    schedule: 'Mon 13:30–15:30',
    room: 'D1-102',
    studentCount: 52,
    status: 'active',
    attendanceRate: 86.3,
  },
  {
    id: 'cls-006',
    code: 'BUS201',
    name: 'Principles of Marketing',
    facultyId: 'business',
    semester: 'HK1 2025-2026',
    schedule: 'Thu 08:00–10:00',
    room: 'E2-205',
    studentCount: 41,
    status: 'active',
    attendanceRate: 89.1,
  },
  {
    id: 'cls-007',
    code: 'ENG301',
    name: 'Thermodynamics',
    facultyId: 'engineering',
    semester: 'HK1 2025-2026',
    schedule: 'Tue 08:00–11:00',
    room: 'Lab-KT-1',
    studentCount: 35,
    status: 'active',
    attendanceRate: 82.0,
  },
  {
    id: 'cls-008',
    code: 'EN201',
    name: 'Academic English II',
    facultyId: 'foreign-lang',
    semester: 'HK1 2025-2026',
    schedule: 'Fri 10:00–12:00',
    room: 'F1-301',
    studentCount: 30,
    status: 'active',
    attendanceRate: 91.5,
  },
];

/** Dữ liệu giả — sinh viên thuộc các lớp giảng viên */
export const MOCK_LECTURER_STUDENTS: LecturerStudent[] = [
  {
    id: 'stu-001',
    studentId: '21110001',
    name: 'Nguyen Van An',
    email: 'an.nguyen@student.edu.vn',
    phone: '0901234567',
    classId: 'cls-001',
    classCode: 'CS101',
    className: 'Introduction to Programming',
    facultyId: 'it',
    status: 'active',
    attendanceRate: 92.5,
    avatar: null,
    initials: 'NA',
  },
  {
    id: 'stu-002',
    studentId: '21110002',
    name: 'Tran Thi Binh',
    email: 'binh.tran@student.edu.vn',
    phone: '0902345678',
    classId: 'cls-001',
    classCode: 'CS101',
    className: 'Introduction to Programming',
    facultyId: 'it',
    status: 'active',
    attendanceRate: 88.0,
    avatar: null,
    initials: 'TB',
  },
  {
    id: 'stu-003',
    studentId: '21110003',
    name: 'Le Hoang Cuong',
    email: 'cuong.le@student.edu.vn',
    phone: '0903456789',
    classId: 'cls-002',
    classCode: 'CS201',
    className: 'Data Structures & Algorithms',
    facultyId: 'it',
    status: 'active',
    attendanceRate: 95.3,
    avatar: null,
    initials: 'LC',
  },
  {
    id: 'stu-004',
    studentId: '21110004',
    name: 'Pham Thi Dung',
    email: 'dung.pham@student.edu.vn',
    phone: '0904567890',
    classId: 'cls-002',
    classCode: 'CS201',
    className: 'Data Structures & Algorithms',
    facultyId: 'it',
    status: 'pending',
    attendanceRate: 78.2,
    avatar: null,
    initials: 'PD',
  },
  {
    id: 'stu-005',
    studentId: '21110005',
    name: 'Vo Minh Em',
    email: 'em.vo@student.edu.vn',
    phone: '0905678901',
    classId: 'cls-003',
    classCode: 'CS301',
    className: 'Software Engineering',
    facultyId: 'it',
    status: 'active',
    attendanceRate: 90.1,
    avatar: null,
    initials: 'VE',
  },
  {
    id: 'stu-006',
    studentId: '21110006',
    name: 'Hoang Thi Phuong',
    email: 'phuong.hoang@student.edu.vn',
    phone: '0906789012',
    classId: 'cls-003',
    classCode: 'CS301',
    className: 'Software Engineering',
    facultyId: 'it',
    status: 'inactive',
    attendanceRate: 65.0,
    avatar: null,
    initials: 'HP',
  },
  {
    id: 'stu-007',
    studentId: '21110007',
    name: 'Dang Van Giang',
    email: 'giang.dang@student.edu.vn',
    phone: '0907890123',
    classId: 'cls-001',
    classCode: 'CS101',
    className: 'Introduction to Programming',
    facultyId: 'it',
    status: 'active',
    attendanceRate: 87.4,
    avatar: null,
    initials: 'DG',
  },
  {
    id: 'stu-008',
    studentId: '21110008',
    name: 'Nguyen Thi Hoa',
    email: 'hoa.nguyen@student.edu.vn',
    phone: '0908901234',
    classId: 'cls-004',
    classCode: 'CS401',
    className: 'Capstone Project',
    facultyId: 'it',
    status: 'active',
    attendanceRate: 100,
    avatar: null,
    initials: 'NH',
  },
  {
    id: 'stu-009',
    studentId: '21120001',
    name: 'Tran Van Khoa',
    email: 'khoa.tran@student.edu.vn',
    phone: '0909012345',
    classId: 'cls-005',
    classCode: 'ECO101',
    className: 'Microeconomics',
    facultyId: 'economics',
    status: 'active',
    attendanceRate: 88.0,
    avatar: null,
    initials: 'TK',
  },
  {
    id: 'stu-010',
    studentId: '21130001',
    name: 'Le Thi Lan',
    email: 'lan.le@student.edu.vn',
    phone: '0910123456',
    classId: 'cls-006',
    classCode: 'BUS201',
    className: 'Principles of Marketing',
    facultyId: 'business',
    status: 'active',
    attendanceRate: 93.2,
    avatar: null,
    initials: 'LL',
  },
];

/** Dữ liệu giả — phiên điểm danh đang mở */
export const MOCK_ATTENDANCE_SESSION: AttendanceSession = {
  id: 'att-001',
  classId: 'cls-001',
  classCode: 'CS101',
  className: 'Introduction to Programming',
  room: 'B2-301',
  startTime: '08:00',
  endTime: '10:00',
  isActive: true,
  totalStudents: 45,
  presentCount: 38,
  absentCount: 7,
  records: [
    { id: 'r-01', studentId: '21110001', name: 'Nguyen Van An', classCode: 'CS101', status: 'present', checkInTime: '07:55', avatar: null, initials: 'NA' },
    { id: 'r-02', studentId: '21110002', name: 'Tran Thi Binh', classCode: 'CS101', status: 'present', checkInTime: '08:02', avatar: null, initials: 'TB' },
    { id: 'r-03', studentId: '21110007', name: 'Dang Van Giang', classCode: 'CS101', status: 'late', checkInTime: '08:15', avatar: null, initials: 'DG' },
    { id: 'r-04', studentId: '21110009', name: 'Tran Van Ich', classCode: 'CS101', status: 'absent', checkInTime: null, avatar: null, initials: 'TI' },
    { id: 'r-05', studentId: '21110010', name: 'Le Thi Kim', classCode: 'CS101', status: 'absent', checkInTime: null, avatar: null, initials: 'LK' },
    { id: 'r-06', studentId: '21110011', name: 'Pham Van Long', classCode: 'CS101', status: 'present', checkInTime: '07:58', avatar: null, initials: 'PL' },
    { id: 'r-07', studentId: '21110012', name: 'Vo Thi Mai', classCode: 'CS101', status: 'excused', checkInTime: null, avatar: null, initials: 'VM' },
    { id: 'r-08', studentId: '21110013', name: 'Hoang Van Nam', classCode: 'CS101', status: 'present', checkInTime: '08:00', avatar: null, initials: 'HN' },
    { id: 'r-09', studentId: '21110014', name: 'Nguyen Thi Oanh', classCode: 'CS101', status: 'absent', checkInTime: null, avatar: null, initials: 'NO' },
    { id: 'r-10', studentId: '21110015', name: 'Tran Van Phuc', classCode: 'CS101', status: 'present', checkInTime: '07:52', avatar: null, initials: 'TP' },
  ],
};

/** Dữ liệu giả — yêu cầu duyệt sinh trắc học */
export const MOCK_BIOMETRIC_REQUESTS: BiometricRequest[] = [
  {
    id: 'bio-001',
    studentId: '21110004',
    studentName: 'Pham Thi Dung',
    classCode: 'CS201',
    submittedAt: '2026-06-01 14:30',
    photoUrl: '',
    status: 'pending',
  },
  {
    id: 'bio-002',
    studentId: '21110016',
    studentName: 'Le Van Quan',
    classCode: 'CS101',
    submittedAt: '2026-06-02 09:15',
    photoUrl: '',
    status: 'pending',
  },
  {
    id: 'bio-003',
    studentId: '21110017',
    studentName: 'Nguyen Thi Suong',
    classCode: 'CS301',
    submittedAt: '2026-05-28 16:45',
    photoUrl: '',
    status: 'approved',
  },
  {
    id: 'bio-004',
    studentId: '21110018',
    studentName: 'Tran Van Tuan',
    classCode: 'CS201',
    submittedAt: '2026-05-27 11:20',
    photoUrl: '',
    status: 'rejected',
    note: 'Blurry photo, face not recognized',
  },
];

/** Dữ liệu giả — feed camera giám sát (placeholder cho video stream) */
export const MOCK_CAMERA_FEEDS: CameraFeed[] = [
  { id: 'cam-01', studentId: '21110001', studentName: 'Nguyen Van An', classCode: 'CS101', isOnline: true, hasViolation: false, lastActivity: '2s ago' },
  { id: 'cam-02', studentId: '21110002', studentName: 'Tran Thi Binh', classCode: 'CS101', isOnline: true, hasViolation: true, lastActivity: '5s ago' },
  { id: 'cam-03', studentId: '21110003', studentName: 'Le Hoang Cuong', classCode: 'CS201', isOnline: true, hasViolation: false, lastActivity: '1s ago' },
  { id: 'cam-04', studentId: '21110005', studentName: 'Vo Minh Em', classCode: 'CS301', isOnline: false, hasViolation: false, lastActivity: 'Offline' },
  { id: 'cam-05', studentId: '21110007', studentName: 'Dang Van Giang', classCode: 'CS101', isOnline: true, hasViolation: false, lastActivity: '3s ago' },
  { id: 'cam-06', studentId: '21110009', studentName: 'Tran Van Ich', classCode: 'CS101', isOnline: true, hasViolation: true, lastActivity: '8s ago' },
  { id: 'cam-07', studentId: '21110011', studentName: 'Pham Van Long', classCode: 'CS101', isOnline: true, hasViolation: false, lastActivity: '2s ago' },
  { id: 'cam-08', studentId: '21110013', studentName: 'Hoang Van Nam', classCode: 'CS101', isOnline: true, hasViolation: false, lastActivity: '4s ago' },
  { id: 'cam-09', studentId: '21110015', studentName: 'Tran Van Phuc', classCode: 'CS101', isOnline: true, hasViolation: false, lastActivity: '1s ago' },
  { id: 'cam-10', studentId: '21110006', studentName: 'Hoang Thi Phuong', classCode: 'CS301', isOnline: true, hasViolation: false, lastActivity: '6s ago' },
  { id: 'cam-11', studentId: '21110008', studentName: 'Nguyen Thi Hoa', classCode: 'CS401', isOnline: true, hasViolation: false, lastActivity: '2s ago' },
  { id: 'cam-12', studentId: '21110020', studentName: 'Le Thi Vy', classCode: 'CS201', isOnline: true, hasViolation: true, lastActivity: '12s ago' },
];

/** Dữ liệu giả — cảnh báo vi phạm */
export const MOCK_VIOLATION_ALERTS: ViolationAlert[] = [
  {
    id: 'vio-001',
    studentId: '21110002',
    studentName: 'Tran Thi Binh',
    classCode: 'CS101',
    type: 'Looking away from screen',
    severity: 'medium',
    timestamp: '08:32:15',
    description: 'Student looking away from proctor screen > 5s',
  },
  {
    id: 'vio-002',
    studentId: '21110009',
    studentName: 'Tran Van Ich',
    classCode: 'CS101',
    type: 'Using mobile phone',
    severity: 'high',
    timestamp: '08:28:42',
    description: 'Object resembling mobile phone detected',
  },
  {
    id: 'vio-003',
    studentId: '21110020',
    studentName: 'Le Thi Vy',
    classCode: 'CS201',
    type: 'Leaving proctored seat',
    severity: 'high',
    timestamp: '08:25:10',
    description: 'Student not present in front of camera > 30s',
  },
  {
    id: 'vio-004',
    studentId: '21110002',
    studentName: 'Tran Thi Binh',
    classCode: 'CS101',
    type: 'Multiple people detected',
    severity: 'low',
    timestamp: '08:20:05',
    description: 'Detected 2 faces in camera frame',
  },
  {
    id: 'vio-005',
    studentId: '21110009',
    studentName: 'Tran Van Ich',
    classCode: 'CS101',
    type: 'Tab switching',
    severity: 'medium',
    timestamp: '08:15:33',
    description: 'Student switched away from the active exam screen',
  },
];

/** Dữ liệu giả — KPI dashboard giảng viên */
export const MOCK_LECTURER_KPIS: LecturerKpi[] = [
  { label: 'Active Classes', value: '6', icon: '📚', colorClass: 'text-blue-bright', bgGlow: 'from-blue/10 to-blue-bright/5', change: '+4 faculties', changeColor: 'text-cyan' },
  { label: 'Total Students', value: '273', icon: '👥', colorClass: 'text-cyan', bgGlow: 'from-cyan/10 to-cyan/5', change: null },
  { label: 'Attendance Today', value: '88.5%', icon: '✅', colorClass: 'text-green', bgGlow: 'from-green/10 to-green/5', change: '+2.3%', changeColor: 'text-green' },
  { label: 'Alerts', value: '5', icon: '🔴', colorClass: 'text-red', bgGlow: 'from-red/10 to-red/5', change: '3 new', changeColor: 'text-red' },
];
