import type { AppNotification } from '../../types/feedback';

/** Dữ liệu giả — thông báo giảng viên */
export const MOCK_LECTURER_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-01',
    type: 'violation',
    title: 'Cảnh báo vi phạm',
    message: 'Tran Thi Binh (CS101) — Nhìn ra ngoài màn hình trong 8 giây',
    time: '2 phút trước',
    read: false,
    initials: 'TB',
    accentColor: '#EF4444',
    actionPath: '/lecture',
  },
  {
    id: 'notif-02',
    type: 'biometric',
    title: 'Sinh trắc học mới',
    message: 'Pham Thi Dung gửi ảnh xác minh — chờ bạn duyệt',
    time: '15 phút trước',
    read: false,
    initials: 'PD',
    accentColor: '#F59E0B',
    actionPath: '/lecture/biometric',
  },
  {
    id: 'notif-03',
    type: 'attendance',
    title: 'Điểm danh CS101',
    message: '38/45 sinh viên có mặt — phiên đang diễn ra',
    time: '32 phút trước',
    read: false,
    initials: 'CS',
    accentColor: '#10B981',
    actionPath: '/lecture/attendance',
  },
  {
    id: 'notif-04',
    type: 'class',
    title: 'Lớp ECO101',
    message: '3 sinh viên mới đăng ký học phần Kinh tế vi mô',
    time: '1 giờ trước',
    read: true,
    initials: 'EC',
    accentColor: '#D97706',
    actionPath: '/lecture/classes',
  },
  {
    id: 'notif-05',
    type: 'violation',
    title: 'Vi phạm cao',
    message: 'Tran Van Ich (CS101) — Phát hiện sử dụng điện thoại',
    time: '2 giờ trước',
    read: true,
    initials: 'TI',
    accentColor: '#EF4444',
    actionPath: '/lecture',
  },
  {
    id: 'notif-06',
    type: 'system',
    title: 'Hệ thống EduGuard',
    message: 'Cập nhật phiên bản giám sát AI v2.1 — độ chính xác +2.3%',
    time: 'Hôm qua',
    read: true,
    initials: 'EG',
    accentColor: '#3B82F6',
  },
];
