import type { AppNotification } from '../../types/feedback';

/** Dữ liệu giả — thông báo giảng viên */
export const MOCK_LECTURER_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-01',
    type: 'violation',
    title: 'Violation Alert',
    message: 'Tran Thi Binh (CS101) — Looking away from screen for 8 seconds',
    time: '2m ago',
    read: false,
    initials: 'TB',
    accentColor: '#EF4444',
    actionPath: '/lecture',
  },
  {
    id: 'notif-02',
    type: 'biometric',
    title: 'New Biometrics',
    message: 'Pham Thi Dung submitted verification photo — pending review',
    time: '15m ago',
    read: false,
    initials: 'PD',
    accentColor: '#F59E0B',
    actionPath: '/lecture/biometric',
  },
  {
    id: 'notif-03',
    type: 'attendance',
    title: 'CS101 Attendance',
    message: '38/45 students present — session active',
    time: '32m ago',
    read: false,
    initials: 'CS',
    accentColor: '#10B981',
    actionPath: '/lecture/attendance',
  },
  {
    id: 'notif-04',
    type: 'class',
    title: 'ECO101 Course',
    message: '3 new students registered for Microeconomics',
    time: '1h ago',
    read: true,
    initials: 'EC',
    accentColor: '#D97706',
    actionPath: '/lecture/classes',
  },
  {
    id: 'notif-05',
    type: 'violation',
    title: 'High Violation',
    message: 'Tran Van Ich (CS101) — Detected mobile phone usage',
    time: '2h ago',
    read: true,
    initials: 'TI',
    accentColor: '#EF4444',
    actionPath: '/lecture',
  },
  {
    id: 'notif-06',
    type: 'system',
    title: 'EduGuard System',
    message: 'AI proctoring v2.1 update — accuracy improved +2.3%',
    time: 'Yesterday',
    read: true,
    initials: 'EG',
    accentColor: '#3B82F6',
  },
];
